name: XPD-Skulls
version: 1.0
main: com.xisumavoid.xpd.skulls.Skulls
author: Autom
description: >
             Spawn in special skulls

commands:
    specialskull:
        description: "Open a menu or type a name"
        aliases: [sps, skull, skulls]
permissions:
    skulls.ownskull:
        description: Allows the user to spawn in his own head
    skulls.specialskull:
        description: Allows the specialskull command
    skulls.update:
        description: Allows the update command
